# Generated by Django 3.0.6 on 2020-05-23 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('member_integral', models.IntegerField(default=0)),
                ('isVIP', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=50)),
                ('menu_price', models.IntegerField()),
                ('menu_integral', models.IntegerField()),
                ('valid', models.IntegerField()),
            ],
            options={
                'db_table': 'Menu',
            },
            managers=[
                ('menuObj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_num', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('valid', models.IntegerField()),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('table', models.IntegerField(default=0)),
                ('server', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('finish', models.IntegerField(default=0)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstage.Member')),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Menu_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_num', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Order')),
            ],
            options={
                'db_table': 'Menu_Order',
            },
        ),
    ]
