# Generated by Django 3.0.6 on 2020-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='menu',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
    ]
