# Generated by Django 3.0.6 on 2020-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_auto_20200601_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_price',
            field=models.FloatField(),
        ),
    ]
